### Health Check
GET http://localhost:3000/api/health

### Listar Usuarios
GET http://localhost:3000/api/users

### Criar usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "nome": "Fernanda",
    "email": "fefe@email.com",
    "password": "1234567"
}

### Buscar usuario por ID
GET http://localhost:3000/api/users/7

### Atualizar usuario
PUT http://localhost:3000/api/users/7
Content-Type: application/json

{
    "nome": "Joana Silva",
    "email": "joana@email.com"
}

### Excluir usuario
DELETE http://localhost:3000/api/users/7