### Health Check
GET http://localhost:3000/api/health

### Listar Usuarios
GET http://localhost:3000/api/users

### Criar usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "nome": "Joana",
    "email": "jo@email.com",
    "senha_hash": "senhaf"
}